name: Build test

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - rusttarget: aarch64-apple-darwin
            zigtarget: aarch64-macos-none
          - rusttarget: x86_64-unknown-linux-gnu
            zigtarget: x86_64-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: neodyland/cross-rust-action@v0.0.7
        with:
          zigtarget: ${{ matrix.zigtarget }}
          rusttarget: ${{ matrix.rusttarget }}
          cargo-build-args: --release
      - name: Rename artifact
        run: |
          mkdir built
          mv target/${{ matrix.rusttarget }}/release/cross-rust-action-test built/cross-rust-action-test
      - uses: actions/upload-artifact@v4
        with:
          name: cross-rust-action-test-${{ matrix.rusttarget }}
          path: built/cross-rust-action-test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: gh run download ${{ github.run_id }} -p cross-rust-action-test-*
      - name: release
        run: |
          gh release create commit-${GITHUB_SHA:0:8} --prerelease cross-rust-action-test-*